### ISSUE TITLE
ModuleNotFoundError: No module named 'nomic' 

### ISSUE THREAD

**Issue by hijazi77** [wombyz/gpt4all_langchain_chatbots#3]
I get this error while running the nomic file every time

Error
> Traceback (most recent call last):
  File "/home/ubuntu/ai_x/gpt4all_langchain_chatbots/nomic_setup.py", line 3, in <module>
    m.open()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nomic/gpt4all/gpt4all.py", line 96, in open
    self.bot = subprocess.Popen(creation_args,
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: PosixPath('/home/ubuntu/.nomic/gpt4all')

can anyone help me with this error

**Comment by g4m3r0** [comment]
@hijazi77 have you installed the nomic package in your enviroment?

`pip install nomic`

**Comment by hijazi77** [comment]
@g4m3r0 already installed, I'm sure

**Comment by g4m3r0** [comment]
@hijazi77 It looks like there are some files and/or permissions missing. I would recommend to uninstall the package and reinstall it again.
I would also recommend to use a virtual environment (venv, conda, etc.) which can be used to "isolate" your packages on a per-project basis. That can prevent potential conflicts between multiple packages or version.
