### ISSUE TITLE
Could not load Llama model from path:

### ISSUE THREAD

**Issue by nizar2yas** [wombyz/gpt4all_langchain_chatbots#9]
I'm getting this error when running the custom_knowledge_query.py: 
llama.cpp: loading model from /Users/XXX/Perso/chatchpt/XX/models/ggml-model-q4_0.bin
error loading model: unexpectedly reached end of file
llama_init_from_file: failed to load model
Traceback (most recent call last):
  File "/Users/XXX/Perso/chatchpt/XXX/custom_knowledge_query.py", line 24, in <module>
    embeddings = LlamaCppEmbeddings(model_path=llama_path)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCppEmbeddings
__root__
  Could not load Llama model from path: /Users/XXX/Perso/chatchpt/XXX/models/ggml-model-q4_0.bin. Received error  (type=value_error)
I checked that the model exist

**Comment by mansigautam777** [comment]
@wombyz  facing the same issue, do you know the fix for it?
